apiVersion: apps/v1
kind: Deployment
metadata:
  name: kenlo-usuarios-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kenlo-usuarios-api
  template:
    metadata:
      labels:
        app: kenlo-usuarios-api
    spec:
      containers:
      - name: kenlo-usuarios-api
        image: registry.digitalocean.com/kenlo/digital-ocean-deploy:<IMAGE_TAG>
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
